<a href="https://colab.research.google.com/github/Vaibhav-sa30/Primer-For-Deep-Learning-Using-Pytorch/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch

In [27]:
from torch import tensor

In [44]:
x = torch.randint(high = 4, size = (3,3), generator =torch.random.manual_seed(42))
print(x)

tensor([[2, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])


In [47]:
y = torch.randint(high = 4, size = (3,3), generator =torch.random.manual_seed(42))
print(y)

tensor([[2, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])


In [49]:
z = torch.randint(high = 4, size = (3,3), generator =torch.random.manual_seed(42))
print(z)

tensor([[2, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])


In [50]:
print(x.shape)
print(x.size())

torch.Size([3, 3])
torch.Size([3, 3])


In [51]:
print(x.ndimension())

2


In [52]:
print(x.device)

cpu


To check whether tensor is placed on cpu or gpu

In [53]:
b = x
print(b is x)

True


In [54]:
print(b)
print(x)

tensor([[2, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])
tensor([[2, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])


In [55]:
b[0,0] = 0

In [56]:
print(x)

tensor([[0, 3, 0],
        [2, 2, 3],
        [0, 0, 2]])


Change in one variable affects other. So be mindful of this.

In [57]:
import copy

In [59]:
b = copy.deepcopy(x)
print(b is x)

False


To negate we can use this

In [ ]:
print(-1*x)

But we should use this. Because it actually changes binary representation of each elements. Without increasing computation.

In [ ]:
print(x.neg())

Apply an activation function

In [60]:
print(torch.sigmoid(x))

tensor([[0.5000, 0.9526, 0.5000],
        [0.8808, 0.8808, 0.9526],
        [0.5000, 0.5000, 0.8808]])


In [61]:
print(x.T)

tensor([[0, 2, 0],
        [3, 2, 0],
        [0, 3, 2]])


Transposeing is a 2D operation. It is easy for 2D but will have to ask which face, if you're doing for higher dimensions

In [64]:
print(torch.transpose(x, 0, 1))

tensor([[0, 2, 0],
        [3, 2, 0],
        [0, 3, 2]])
